---
all:
  hosts:
    boxxy:
      ansible_host:               10.85.0.77
    analab:
      ansible_host:               10.85.0.88
    c7automized:  #Testinf if i can use comments here
      ansible_host:               10.85.0.89
    rhel7:
      ansible_host:               10.85.0.79
    rootca:
      ansible_host:               10.85.0.11
    rhel6:
      ansible_host:               10.85.0.69
  vars:
    ansible_port: 22                 #Theese vars could be  in a separate file cin group_vars/all
  children:
    ungrouped:
      hosts:
        boxxy:
    all_linux:
      hosts:
        c7automized:
        boxxy:
        rhel7:
    all_linux_but_me:
      hosts:
        boxxy:
        rhel7:
        rootca:
    trinity:
      hosts:
        c7automized:
        analab:
        rhel7:


        
        
